name = "MPISchurComplements"
uuid = "586db363-8230-43f3-b4b3-2c5432ab38c6"
authors = ["John Omotani <john.omotani@ukaea.uk>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
LinearAlgebra = "1.11.0"
MPI = "0.20.23"
Primes = "0.5.7"
SparseArrays = "1.11.0"
StableRNGs = "1"
TimerOutputs = "0.5.29"

[extras]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Primes", "StableRNGs", "Test"]
